general:
  branches:
    ignore:
      - gh-pages

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/udacidrone

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "circleci_requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r circleci_requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "circleci_requirements.txt" }}

      - run:
          name: lint
          command: |
            . venv/bin/activate
            make lint
        
      - run:
          name: test
          command: |
            . venv/bin/activate
            make test

      # - run:
      #     name: format
      #     command: |
      #       . venv/bin/activate
      #       make format

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy-website:
    docker:
      - image: circleci/node:6.10.3
    working_directory: ~/udacidrone
    steps:
      - checkout
      - run:
          name: deploy website
          command: |
            git config --global user.email "adrienp@users.noreply.github.com"
            git config --global user.name "Adrien Perkins"
            echo "machine github.com login adrienp password $TOKEN_ADRIEN" > ~/.netrc
            cd website && yarn --pure-lockfile && GIT_USER=adrienp USE_SSH=false yarn run publish-gh-pages


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-website:
          filters:
            branches:
              only: master
